#!/bin/sh

python manage.py dumpdata core -e core.Attempt -e core.Token -e core.TestSolveSession --format yaml -o core/fixtures/$(date +"%Y%m%d").yaml
python manage.py dumpdata info --format yaml -o info/fixtures/$(date +"%Y%m%d").yaml
