#!/bin/sh

# If you aren't Evan, replace the bucket name...
(
  cd typescripts/ || exit
  tsc
)
python manage.py tailwind build
python manage.py collectstatic
gcloud storage rsync -R static/ gs://mosp.evanchen.cc/static
