# Generated by Django 3.2.4 on 2021-06-27 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField(help_text='The number of the hunt', unique=True)),
                ('name', models.CharField(help_text='The name of this hunt.', max_length=80)),
                ('authors', models.CharField(help_text='The credits for this hunt.', max_length=255)),
                ('description', models.TextField(help_text='The text to display for this hunt.')),
                ('start_date', models.DateTimeField(help_text='When the hunt can be started.')),
                ('visible', models.BooleanField(help_text="Whether the hunt is visible to people; use false if you're just testing.")),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('hunt', models.ForeignKey(help_text='The hunt that this round belongs to', on_delete=django.db.models.deletion.CASCADE, to='core.hunt')),
            ],
        ),
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('slug', models.SlugField(help_text='The slug for the puzzle')),
                ('answer', models.CharField(help_text='Display answer to the puzzle', max_length=80)),
                ('answer_salt', models.SmallIntegerField(help_text='A random four-digit number')),
                ('icon', models.CharField(blank=True, help_text='The icon associated to this puzzle', max_length=5)),
                ('place', models.CharField(blank=True, help_text='The location associated to this puzzle', max_length=80)),
                ('visible_when_unlocked', models.BooleanField(default=True, help_text='Show the puzzle on the index when unlocked?')),
                ('unlock_threshold', models.IntegerField(default=0, help_text='Amount of courage needed to unlock')),
                ('unlock_date', models.DateTimeField(help_text='When the puzzle can be unlocked', null=True)),
                ('courage_bounty', models.IntegerField(default=25, help_text='Amount of courage obtained by solving')),
                ('content', models.TextField(blank=True, help_text='Markdown for the puzzle content')),
                ('solution', models.TextField(blank=True, help_text='Markdown for the puzzle solution')),
                ('author_notes', models.TextField(blank=True, help_text="Markdown for the author's notes")),
                ('post_solve_story', models.TextField(blank=True, help_text='Markdown for the post-solve story')),
                ('pre_solve_story', models.TextField(blank=True, help_text='Markdown for the pre-solve story')),
                ('puzzle_head', models.TextField(help_text='Extra HTML to include in <head>')),
                ('unit', models.ForeignKey(help_text='The round that this puzzle belongs to', on_delete=django.db.models.deletion.CASCADE, to='core.unit')),
            ],
        ),
    ]
