# Generated by Django 3.2.4 on 2021-06-27 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puzzle',
            name='visible_when_unlocked',
        ),
        migrations.AddField(
            model_name='puzzle',
            name='force_visibility',
            field=models.BooleanField(help_text='If True, always show; if False, always hide', null=True),
        ),
    ]
