# Generated by Django 3.2.4 on 2021-06-27 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210627_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='place_slug',
            field=models.SlugField(default='idk', help_text='Slug for the location in the map'),
            preserve_default=False,
        ),
    ]
