# Generated by Django 3.2.4 on 2021-06-29 15:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_puzzle_place_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='puzzle',
            name='unit',
        ),
        migrations.AddField(
            model_name='puzzle',
            name='hunt',
            field=models.ForeignKey(default=1, help_text='The hunt that this puzzle belongs to', on_delete=django.db.models.deletion.CASCADE, to='core.hunt'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='puzzle',
            name='is_meta',
            field=models.BooleanField(default=False, help_text='Whether this is a metapuzzle.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='puzzle',
            name='parent',
            field=models.ForeignKey(help_text='If this is nonempty, specifies a parent. If null, then this puzzle is really a round.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.puzzle'),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='unlock_needs',
            field=models.ForeignKey(help_text='If this is nonempty, then unlock only when the target puzzle is done.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_on', to='core.puzzle'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='answer',
            field=models.CharField(blank=True, help_text='Display answer to the puzzle Should be blank for rounds', max_length=80),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='answer_salt',
            field=models.SmallIntegerField(default=0, help_text='A random number from 0000 to 9999'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='content',
            field=models.TextField(blank=True, help_text='Markdown for the puzzle content.'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='courage_bounty',
            field=models.IntegerField(default=25, help_text='Amount of courage obtained by solving.'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='force_visibility',
            field=models.BooleanField(help_text='If True, always show; if False, always hide.', null=True),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='slug',
            field=models.SlugField(help_text='The slug for the puzzle or round.'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='solution',
            field=models.TextField(blank=True, help_text='Markdown for the puzzle solution.'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='unlock_date',
            field=models.DateTimeField(help_text='When the puzzle can be unlocked.', null=True),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='unlock_threshold',
            field=models.IntegerField(default=0, help_text='Amount of courage needed to unlock.'),
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
