# Generated by Django 3.2.4 on 2021-06-29 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210629_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.PositiveSmallIntegerField(help_text='The cost of the hint (patience)')),
                ('question', models.CharField(help_text='The question that the hint is for.', max_length=120)),
                ('answer', models.CharField(help_text='The content of the hint.', max_length=120)),
                ('time_until', models.PositiveSmallIntegerField(help_text='Minutes until the hint is visible.')),
            ],
        ),
        migrations.AddField(
            model_name='token',
            name='name',
            field=models.CharField(default='Steve', help_text='Who are you?', max_length=128),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Solve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_guesses', models.TextField(help_text='Newline separated list of answer guesses')),
                ('unlocked_on', models.DateTimeField(help_text='When this puzzle was unlocked', null=True)),
                ('solved_on', models.DateTimeField(help_text='When this puzzle was solved', null=True)),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.puzzle')),
                ('token', models.ForeignKey(help_text='The token this solve attempt is for', on_delete=django.db.models.deletion.CASCADE, to='core.token')),
            ],
        ),
        migrations.AddField(
            model_name='token',
            name='hints_obtained',
            field=models.ManyToManyField(help_text='Hints purchased by this token', to='core.Hint'),
        ),
    ]
