# Generated by Django 3.2.4 on 2021-07-02 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210629_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hint',
            old_name='time_until',
            new_name='minutes_until_unlock',
        ),
    ]
