# Generated by Django 3.2.4 on 2021-07-03 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_time_until_hint_minutes_until_unlock'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='is_round',
            field=models.BooleanField(default=False, help_text='Whether this is a round container.'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='is_meta',
            field=models.BooleanField(default=False, help_text='Whether this is a metapuzzle.'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='parent',
            field=models.ForeignKey(help_text='Specifies a parent round. ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.puzzle'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='unlock_needs',
            field=models.ForeignKey(help_text='If this is nonempty, then unlock only when the target puzzle or round is done.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_on', to='core.puzzle'),
        ),
    ]
