# Generated by Django 3.2.4 on 2021-07-03 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210703_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hunt',
            name='description',
            field=models.TextField(blank=True, help_text='The text to display for this hunt.'),
        ),
        migrations.AlterField(
            model_name='hunt',
            name='name',
            field=models.CharField(blank=True, help_text='The name of this hunt.', max_length=80),
        ),
    ]
