# Generated by Django 4.1.7 on 2023-03-07 21:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_auto_20220430_2135"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testsolvesession",
            name="puzzle",
        ),
        migrations.RemoveField(
            model_name="token",
            name="attempts",
        ),
        migrations.RemoveField(
            model_name="token",
            name="hints_obtained",
        ),
        migrations.RemoveField(
            model_name="token",
            name="user",
        ),
        migrations.RemoveField(
            model_name="puzzle",
            name="status_progress",
        ),
        migrations.AlterField(
            model_name="puzzle",
            name="is_meta",
            field=models.BooleanField(default=False, help_text="Is this a metapuzzle?"),
        ),
        migrations.DeleteModel(
            name="Attempt",
        ),
        migrations.DeleteModel(
            name="Hint",
        ),
        migrations.DeleteModel(
            name="TestSolveSession",
        ),
        migrations.DeleteModel(
            name="Token",
        ),
    ]
