# Generated by Django 3.2.4 on 2021-07-03 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210703_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='place_slug',
            field=models.SlugField(blank=True, help_text='Slug for the location in the map'),
        ),
    ]
