# Generated by Django 3.2.4 on 2021-07-03 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_puzzle_place_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='place_slug',
            field=models.SlugField(blank=True, help_text='Slug for the location in the map', null=True),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='unlock_date',
            field=models.DateTimeField(blank=True, help_text='When the puzzle can be unlocked.', null=True),
        ),
    ]
