# Generated by Django 3.2.4 on 2021-07-03 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210703_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='puzzle_head',
            field=models.TextField(blank=True, help_text='Extra HTML to include in <head>'),
        ),
    ]
