# Generated by Django 3.2.4 on 2021-07-03 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_puzzle_puzzle_head'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puzzle',
            name='courage_bounty',
        ),
        migrations.RemoveField(
            model_name='puzzle',
            name='force_visibility',
        ),
        migrations.RemoveField(
            model_name='puzzle',
            name='hunt',
        ),
        migrations.RemoveField(
            model_name='puzzle',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='puzzle',
            name='is_round',
        ),
        migrations.RemoveField(
            model_name='puzzle',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='puzzle',
            name='place',
        ),
        migrations.RemoveField(
            model_name='puzzle',
            name='place_slug',
        ),
        migrations.RemoveField(
            model_name='puzzle',
            name='unlock_date',
        ),
        migrations.RemoveField(
            model_name='puzzle',
            name='unlock_needs',
        ),
        migrations.RemoveField(
            model_name='puzzle',
            name='unlock_threshold',
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='answer',
            field=models.CharField(help_text='Display answer to the puzzle', max_length=80),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='slug',
            field=models.SlugField(help_text='The slug for the puzzle.'),
        ),
        migrations.CreateModel(
            name='Unlockable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name for this unlockable (e.g. place on map).', max_length=80)),
                ('slug', models.SlugField(help_text='The slug for the unlockable.')),
                ('icon', models.CharField(blank=True, help_text='Emoji for this unlockable.', max_length=5)),
                ('unlock_threshold', models.IntegerField(default=0, help_text='Amount of courage needed to unlock.')),
                ('unlock_date', models.DateTimeField(blank=True, help_text='When the unlockable can be unlocked.', null=True)),
                ('force_visibility', models.BooleanField(blank=True, help_text='Always show or hide', null=True)),
                ('courage_bounty', models.IntegerField(default=25, help_text='Amount of courage obtained by solving.')),
                ('hunt', models.ForeignKey(help_text='The hunt this unlockable belongs to', on_delete=django.db.models.deletion.CASCADE, to='core.hunt')),
                ('parent', models.ForeignKey(help_text='Specifies a parent unlockable. ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.unlockable')),
                ('unlock_needs', models.ForeignKey(help_text='If this is nonempty, then unlock only when the target is done.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_on', to='core.unlockable')),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('number', models.SmallIntegerField(help_text='Chapter number for flavor')),
                ('content', models.TextField(blank=True, help_text='Any text to show in the round page')),
                ('slug', models.SlugField(help_text='The slug for the round.')),
                ('unlockable', models.OneToOneField(help_text='Associated unlockable for this round.', on_delete=django.db.models.deletion.CASCADE, to='core.unlockable')),
            ],
        ),
        migrations.AddField(
            model_name='puzzle',
            name='unlockable',
            field=models.OneToOneField(default=None, help_text='Associated unlockable for this puzzle.', on_delete=django.db.models.deletion.CASCADE, to='core.unlockable'),
            preserve_default=False,
        ),
    ]
