# Generated by Django 3.2.4 on 2021-07-03 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210703_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hint',
            name='answer',
            field=models.CharField(help_text='The content of the hint', max_length=120),
        ),
        migrations.AlterField(
            model_name='hint',
            name='minutes_until_unlock',
            field=models.PositiveSmallIntegerField(help_text='Minutes until the hint is visible'),
        ),
        migrations.AlterField(
            model_name='hint',
            name='question',
            field=models.CharField(help_text='The question that the hint is for', max_length=120),
        ),
        migrations.AlterField(
            model_name='hunt',
            name='authors',
            field=models.CharField(help_text='The credits for this hunt', max_length=255),
        ),
        migrations.AlterField(
            model_name='hunt',
            name='description',
            field=models.TextField(blank=True, help_text='The text to display for this hunt'),
        ),
        migrations.AlterField(
            model_name='hunt',
            name='name',
            field=models.CharField(blank=True, help_text='The name of this hunt', max_length=80),
        ),
        migrations.AlterField(
            model_name='hunt',
            name='start_date',
            field=models.DateTimeField(help_text='When the hunt can be started'),
        ),
        migrations.AlterField(
            model_name='hunt',
            name='visible',
            field=models.BooleanField(help_text="Whether the hunt is visible to people; use false if you're just testing"),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='content',
            field=models.TextField(blank=True, help_text='Markdown for the puzzle content'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='is_meta',
            field=models.BooleanField(default=False, help_text='Whether this is a metapuzzle'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='slug',
            field=models.SlugField(help_text='The slug for the puzzle'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='solution',
            field=models.TextField(blank=True, help_text='Markdown for the puzzle solution'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='unlockable',
            field=models.OneToOneField(help_text='Associated unlockable for this puzzle', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.unlockable'),
        ),
        migrations.AlterField(
            model_name='round',
            name='slug',
            field=models.SlugField(help_text='The slug for the round'),
        ),
        migrations.AlterField(
            model_name='round',
            name='unlockable',
            field=models.OneToOneField(help_text='Associated unlockable for this round', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.unlockable'),
        ),
        migrations.AlterField(
            model_name='unlockable',
            name='courage_bounty',
            field=models.IntegerField(default=25, help_text='Amount of courage obtained by solving'),
        ),
        migrations.AlterField(
            model_name='unlockable',
            name='icon',
            field=models.CharField(blank=True, help_text='Emoji for this unlockable', max_length=5),
        ),
        migrations.AlterField(
            model_name='unlockable',
            name='name',
            field=models.CharField(help_text='The name for this unlockable (e.g. place on map)', max_length=80),
        ),
        migrations.AlterField(
            model_name='unlockable',
            name='parent',
            field=models.ForeignKey(help_text='Specifies a parent unlockable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.unlockable'),
        ),
        migrations.AlterField(
            model_name='unlockable',
            name='slug',
            field=models.SlugField(help_text='The slug for the unlockable'),
        ),
        migrations.AlterField(
            model_name='unlockable',
            name='unlock_date',
            field=models.DateTimeField(blank=True, help_text='When the unlockable can be unlocked', null=True),
        ),
        migrations.AlterField(
            model_name='unlockable',
            name='unlock_needs',
            field=models.ForeignKey(help_text='If this is nonempty, then unlock only when the target is done', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_on', to='core.unlockable'),
        ),
        migrations.AlterField(
            model_name='unlockable',
            name='unlock_threshold',
            field=models.IntegerField(default=0, help_text='Amount of courage needed to unlock'),
        ),
    ]
