# Generated by Django 3.2.4 on 2021-07-03 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210703_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='unlockable',
            field=models.OneToOneField(blank=True, help_text='Associated unlockable for this puzzle', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.unlockable'),
        ),
        migrations.AlterField(
            model_name='round',
            name='unlockable',
            field=models.OneToOneField(blank=True, help_text='Associated unlockable for this round', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.unlockable'),
        ),
        migrations.AlterField(
            model_name='unlockable',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Specifies a parent unlockable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.unlockable'),
        ),
        migrations.AlterField(
            model_name='unlockable',
            name='unlock_needs',
            field=models.ForeignKey(blank=True, help_text='If this is nonempty, then unlock only when the target is done', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_on', to='core.unlockable'),
        ),
    ]
