# Generated by Django 3.2.4 on 2021-07-03 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210703_0111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='round',
            old_name='label_number',
            new_name='chapter_number',
        ),
        migrations.RemoveField(
            model_name='hunt',
            name='number',
        ),
        migrations.AddField(
            model_name='hunt',
            name='volume_number',
            field=models.CharField(default='I', help_text='The volume number corresponding to this hunt', max_length=80, unique=True),
            preserve_default=False,
        ),
    ]
