# Generated by Django 3.2.4 on 2021-07-03 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20210703_0117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='puzzle',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='round',
            old_name='title',
            new_name='name',
        ),
    ]
