# Generated by Django 3.2.4 on 2021-07-03 02:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20210703_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solve',
            name='unlocked_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='When this puzzle was unlocked'),
            preserve_default=False,
        ),
    ]
