# Generated by Django 3.2.4 on 2021-07-03 04:02

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20210703_0227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puzzle',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='puzzle',
            name='answer_salt',
        ),
        migrations.AlterField(
            model_name='round',
            name='chapter_number',
            field=models.CharField(help_text='Chapter number for flavor', max_length=80, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='solve',
            unique_together={('token', 'unlockable')},
        ),
        migrations.CreateModel(
            name='SaltedAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_answer', models.CharField(help_text='Display answer to the puzzle', max_length=80)),
                ('salt', models.SmallIntegerField(default=core.models._rand, help_text='A random number from 0000 to 9999')),
                ('is_final', models.BooleanField(default=True, help_text='Whether this is a full answer or partial answer.')),
                ('message', models.CharField(blank=True, help_text='For partial answers, the nudge to provide solvers.', max_length=256)),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salted_answers', to='core.puzzle')),
            ],
            options={
                'unique_together': {('puzzle', 'salt')},
            },
        ),
    ]
