# Generated by Django 3.2.4 on 2021-07-03 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20210703_0402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saltedanswer',
            name='is_final',
        ),
    ]
