# Generated by Django 3.2.4 on 2021-07-03 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_saltedanswer_is_final'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(-1, 'Found'), (0, 'Unlocked'), (1, 'Solved')], default=-1)),
                ('token', models.ForeignKey(help_text='The token this attempt is for', on_delete=django.db.models.deletion.CASCADE, to='core.token')),
                ('unlockable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unlockable')),
            ],
        ),
        migrations.DeleteModel(
            name='Solve',
        ),
        migrations.AddField(
            model_name='token',
            name='attempts',
            field=models.ManyToManyField(help_text='Attempts attached to this token', through='core.Attempt', to='core.Unlockable'),
        ),
    ]
