# Generated by Django 3.2.4 on 2021-07-03 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20210703_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='post_solve_image_alt',
            field=models.TextField(blank=True, help_text='Static path to the post-solve image'),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='post_solve_image_path',
            field=models.CharField(blank=True, help_text='Static path to the post-solve image', max_length=240),
        ),
        migrations.AlterField(
            model_name='unlockable',
            name='unlock_needs',
            field=models.ForeignKey(blank=True, help_text='If this is nonempty, then unlock only when the target is done', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocking', to='core.unlockable'),
        ),
    ]
