# Generated by Django 3.2.4 on 2021-07-03 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20210703_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='display_answer',
            field=models.CharField(default='ANSWER', help_text='Display answer for the puzzle', max_length=128),
            preserve_default=False,
        ),
    ]
