# Generated by Django 3.2.4 on 2021-07-03 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_puzzle_display_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puzzle',
            name='author_notes',
        ),
        migrations.RemoveField(
            model_name='puzzle',
            name='post_solve_image_alt',
        ),
        migrations.RemoveField(
            model_name='puzzle',
            name='post_solve_image_path',
        ),
        migrations.RemoveField(
            model_name='puzzle',
            name='post_solve_story',
        ),
        migrations.RemoveField(
            model_name='puzzle',
            name='solution',
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_solve_story', models.TextField(blank=True, help_text='Markdown for the post-solve story')),
                ('solution_text', models.TextField(blank=True, help_text='Markdown for the puzzle solution')),
                ('author_notes', models.TextField(blank=True, help_text="Markdown for the author's notes")),
                ('post_solve_image_path', models.CharField(blank=True, help_text='Static path to the post-solve image', max_length=240)),
                ('post_solve_image_alt', models.TextField(blank=True, help_text='Static path to the post-solve image')),
                ('puzzle', models.OneToOneField(help_text='The puzzle this is a solution for', on_delete=django.db.models.deletion.CASCADE, to='core.puzzle')),
            ],
        ),
    ]
