# Generated by Django 3.2.4 on 2021-07-04 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20210703_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='hunt',
            name='allow_skip',
            field=models.BooleanField(default=False, help_text='Whether to allow `skip puzzle`'),
        ),
        migrations.AlterField(
            model_name='hunt',
            name='visible',
            field=models.BooleanField(default=False, help_text="Whether the hunt is visible to people; use false if you're just testing"),
        ),
    ]
