# Generated by Django 3.2.4 on 2021-07-04 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20210704_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='slug',
            field=models.SlugField(help_text='The slug for the puzzle', unique=True),
        ),
        migrations.AlterField(
            model_name='round',
            name='slug',
            field=models.SlugField(help_text='The slug for the round', unique=True),
        ),
        migrations.AlterField(
            model_name='unlockable',
            name='slug',
            field=models.SlugField(help_text='The slug for the unlockable', unique=True),
        ),
    ]
