# Generated by Django 3.2.4 on 2021-07-04 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20210704_0316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='round',
            old_name='content',
            new_name='summary_text',
        ),
        migrations.AddField(
            model_name='round',
            name='round_text',
            field=models.TextField(blank=True, help_text='Markdown for content in the round page.'),
        ),
        migrations.AlterField(
            model_name='unlockable',
            name='courage_bounty',
            field=models.IntegerField(default=25, help_text='Amount of courage obtained by solving', verbose_name='Bounty'),
        ),
        migrations.AlterField(
            model_name='unlockable',
            name='force_visibility',
            field=models.BooleanField(blank=True, help_text='Always show or hide', null=True, verbose_name='Show'),
        ),
        migrations.AlterUniqueTogether(
            name='attempt',
            unique_together={('token', 'unlockable')},
        ),
    ]
