# Generated by Django 3.2.4 on 2021-07-04 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20210704_0400'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='intro_story_text',
            field=models.TextField(blank=True, help_text='Markdown for the pre-entry story'),
        ),
        migrations.AlterField(
            model_name='round',
            name='round_text',
            field=models.TextField(blank=True, help_text='Markdown for content in the round page'),
        ),
    ]
