# Generated by Django 3.2.4 on 2021-07-05 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20210704_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='hashed_passphrase',
            field=models.CharField(default='blargh', help_text='Hashed passphrase', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='token',
            unique_together={('name', 'hashed_passphrase')},
        ),
    ]
