# Generated by Django 3.2.4 on 2021-07-05 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20210705_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='reduced_name',
            field=models.CharField(default='qutebrowser', help_text='Name with only [a-z][0-9] characters.', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='token',
            unique_together={('reduced_name', 'hashed_passphrase')},
        ),
    ]
