# Generated by Django 3.2.4 on 2021-07-05 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20210705_0234'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='found_on',
            field=models.DateTimeField(blank=True, help_text='When the unlockable is found', null=True),
        ),
        migrations.AddField(
            model_name='attempt',
            name='solved_on',
            field=models.DateTimeField(blank=True, help_text='When the unlockable is unlocked', null=True),
        ),
        migrations.AddField(
            model_name='attempt',
            name='unlocked_on',
            field=models.DateTimeField(blank=True, help_text='When the unlockable is unlocked', null=True),
        ),
    ]
