# Generated by Django 3.2.4 on 2021-07-05 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20210705_0343'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Turn off to prevent the token from being used'),
        ),
    ]
