# Generated by Django 3.2.4 on 2021-07-05 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_token_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='passphrase',
            field=models.CharField(help_text='Magic word needed to retrieve progress', max_length=256, verbose_name='Magic word'),
        ),
    ]
