# Generated by Django 3.2.5 on 2021-07-15 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_token_reduced_passphrase'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='token',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='token',
            name='passphrase',
        ),
        migrations.RemoveField(
            model_name='token',
            name='reduced_passphrase',
        ),
    ]
