# Generated by Django 3.2.5 on 2021-07-19 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_auto_20210719_0314'),
    ]

    operations = [
        migrations.AddField(
            model_name='unlockable',
            name='story_only',
            field=models.BooleanField(default=False, help_text='If this unlockable is story only'),
        ),
    ]
