# Generated by Django 3.2.5 on 2021-07-19 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_unlockable_story_only'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unlockable',
            options={'ordering': ('sort_order',)},
        ),
        migrations.AddField(
            model_name='unlockable',
            name='sort_order',
            field=models.SmallIntegerField(default=50, help_text='An integer to sort this unlockable by in the listing'),
        ),
    ]
