# Generated by Django 3.2.5 on 2021-07-19 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_auto_20210719_0341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unlockable',
            options={'ordering': ('sort_order', 'name')},
        ),
    ]
