# Generated by Django 3.2.5 on 2021-07-19 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_auto_20210719_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unlockable',
            name='on_solve_link_to',
            field=models.ForeignKey(blank=True, help_text='When solved, link to this round instead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redirected_by', to='core.round'),
        ),
        migrations.AlterField(
            model_name='unlockable',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Specifies a parent round', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.round'),
        ),
    ]
