# Generated by Django 3.2.5 on 2021-07-19 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_auto_20210719_0513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puzzle',
            name='display_answer',
        ),
        migrations.AddField(
            model_name='saltedanswer',
            name='is_canonical',
            field=models.BooleanField(default=False, help_text='Make this the answer printed by the website for solvers'),
        ),
        migrations.AddField(
            model_name='saltedanswer',
            name='is_final',
            field=models.BooleanField(default=False, help_text='Make an answer final; solver marks as correct if seen'),
        ),
        migrations.AlterField(
            model_name='saltedanswer',
            name='message',
            field=models.CharField(blank=True, help_text='For partial answers, the nudge to provide solvers', max_length=256),
        ),
    ]
