# Generated by Django 3.2.5 on 2021-07-19 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_auto_20210719_0540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saltedanswer',
            name='is_final',
        ),
        migrations.AddField(
            model_name='saltedanswer',
            name='is_correct',
            field=models.BooleanField(default=True, help_text='Make an answer correct; solver marks as correct if seen.'),
        ),
        migrations.AlterField(
            model_name='saltedanswer',
            name='is_canonical',
            field=models.BooleanField(default=True, help_text='Make this the answer printed by the website for solvers'),
        ),
    ]
