# Generated by Django 3.2.5 on 2021-07-19 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_auto_20210719_0549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hunt',
            name='description',
        ),
        migrations.RemoveField(
            model_name='round',
            name='summary_text',
        ),
    ]
