# Generated by Django 3.2.5 on 2021-07-19 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_auto_20210719_0724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puzzle',
            name='pre_solve_story',
        ),
    ]
