# Generated by Django 3.2.5 on 2021-07-20 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_remove_puzzle_pre_solve_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='post_solve_image_alt',
            field=models.TextField(blank=True, help_text='Alt text for the post-solve image'),
        ),
    ]
