# Generated by Django 3.2.5 on 2021-07-20 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_alter_solution_post_solve_image_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='flavor_text',
            field=models.TextField(blank=True, help_text='Markdown for puzzle flavor text'),
        ),
    ]
