# Generated by Django 3.2.5 on 2021-07-24 00:09

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_puzzle_flavor_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='content',
            field=markdownx.models.MarkdownxField(blank=True, help_text='Markdown for the puzzle content'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='flavor_text',
            field=markdownx.models.MarkdownxField(blank=True, help_text='Markdown for puzzle flavor text'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='puzzle_head',
            field=models.TextField(blank=True, help_text='Extra HTML to include in HTML header'),
        ),
        migrations.AlterField(
            model_name='round',
            name='round_text',
            field=markdownx.models.MarkdownxField(blank=True, help_text='Markdown for content in the round page'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='author_notes',
            field=markdownx.models.MarkdownxField(blank=True, help_text="Markdown for the author's notes"),
        ),
        migrations.AlterField(
            model_name='solution',
            name='post_solve_image_alt',
            field=models.CharField(blank=True, help_text='Alt text for the post-solve image', max_length=240),
        ),
        migrations.AlterField(
            model_name='solution',
            name='post_solve_story',
            field=markdownx.models.MarkdownxField(blank=True, help_text='Markdown for the post-solve story'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='solution_text',
            field=markdownx.models.MarkdownxField(blank=True, help_text='Markdown for the puzzle solution'),
        ),
        migrations.AlterField(
            model_name='unlockable',
            name='intro_story_text',
            field=markdownx.models.MarkdownxField(blank=True, help_text='Markdown for the pre-entry story'),
        ),
    ]
