big_color_list = [
	('a8bb19', 'black', 'Acid Green'),
	('7cb9e8', 'black', 'Aero'),
	('c9ffe5', 'black', 'Aero Blue'),
	('b284be', 'black', 'African Purple'),
	('5d8aa8', 'black', 'Air Force Blue'),
	('00308f', 'white', 'Air Force Blue'),
	('72a0c1', 'black', 'Air Superiority Blue'),
	('a32638', 'white', 'Alabama Crimson'),
	('f0f8ff', 'black', 'Alice Blue'),
	('e32636', 'white', 'Alizarin Crimson'),
	('c46210', 'white', 'Alloy Orange'),
	('efdecd', 'black', 'Almond'),
	('9f2b68', 'white', 'Amaranth'),
	('f19cbb', 'black', 'Amaranth Pink'),
	('ab274f', 'white', 'Amaranth Purple'),
	('3b7a57', 'white', 'Amazon'),
	('ffbf00', 'black', 'Amber'),
	('ff7e00', 'black', 'Amber'),
	('ff033e', 'white', 'American Rose'),
	('9966cc', 'white', 'Amethyst'),
	('a4c639', 'black', 'Android Green'),
	('f2f3f4', 'black', 'Anti-flash White'),
	('cd9575', 'black', 'Antique Brass'),
	('665d1e', 'white', 'Antique Bronze'),
	('915c83', 'white', 'Antique Fuchsia'),
	('841b2d', 'white', 'Antique Ruby'),
	('faebd7', 'black', 'Antique White'),
	('008000', 'white', 'Ao'),
	('8db600', 'black', 'Apple Green'),
	('fbceb1', 'black', 'Apricot'),
	('00ffff', 'black', 'Aqua'),
	('7fffd4', 'black', 'Aquamarine'),
	('4b5320', 'white', 'Army Green'),
	('3b444b', 'white', 'Arsenic'),
	('8f9779', 'black', 'Artichoke'),
	('e9d66b', 'black', 'Arylide Yellow'),
	('b2beb5', 'black', 'Ash Grey'),
	('87a96b', 'black', 'Asparagus'),
	('ff9966', 'black', 'Atomic Tangerine'),
	('a52a2a', 'white', 'Auburn'),
	('fdee00', 'black', 'Aureolin'),
	('6e7f80', 'white', 'AuroMetalSaurus'),
	('568203', 'white', 'Avocado'),
	('007fff', 'white', 'Azure'),
	('f0ffff', 'black', 'Azure Mist'),
	('2e5894', 'white', "B'dazzled Blue"),
	('89cff0', 'black', 'Baby Blue'),
	('a1caf1', 'black', 'Baby Blue Eyes'),
	('f4c2c2', 'black', 'Baby Pink'),
	('fefefa', 'black', 'Baby Powder'),
	('ff91af', 'black', 'Baker-Miller Pink'),
	('21abcd', 'black', 'Ball Blue'),
	('fae7b5', 'black', 'Banana Mania'),
	('ffe135', 'black', 'Banana Yellow'),
	('006a4e', 'white', 'Bangladesh Green'),
	('e0218a', 'white', 'Barbie Pink'),
	('7c0a02', 'white', 'Barn Red'),
	('848482', 'black', 'Battleship Grey'),
	('98777b', 'white', 'Bazaar'),
	('bcd4e6', 'black', 'Beau Blue'),
	('9f8170', 'black', 'Beaver'),
	('f5f5dc', 'black', 'Beige'),
	('9c2542', 'white', "Big Dip O'ruby"),
	('ffe4c4', 'black', 'Bisque'),
	('3d2b1f', 'white', 'Bistre'),
	('967117', 'white', 'Bistre Brown'),
	('cae00d', 'black', 'Bitter Lemon'),
	('648c11', 'white', 'Bitter Lime'),
	('fe6f5e', 'black', 'Bittersweet'),
	('bf4f51', 'white', 'Bittersweet Shimmer'),
	('000000', 'white', 'Black'),
	('3d0c02', 'white', 'Black Bean'),
	('253529', 'white', 'Black Leather Jacket'),
	('3b3c36', 'white', 'Black Olive'),
	('ffebcd', 'black', 'Blanched Almond'),
	('a57164', 'white', 'Blast-off Bronze'),
	('318ce7', 'black', 'Bleu De France'),
	('ace5ee', 'black', 'Blizzard Blue'),
	('faf0be', 'black', 'Blond'),
	('0000ff', 'white', 'Blue'),
	('1f75fe', 'white', 'Blue'),
	('0093af', 'black', 'Blue'),
	('0087bd', 'white', 'Blue'),
	('0247fe', 'white', 'Blue'),
	('333399', 'white', 'Blue'),
	('a2a2d0', 'black', 'Blue Bell'),
	('126180', 'white', 'Blue Sapphire'),
	('5072a7', 'white', 'Blue Yonder'),
	('6699cc', 'black', 'Blue-gray'),
	('0d98ba', 'black', 'Blue-green'),
	('8a2be2', 'white', 'Blue-violet'),
	('4f86f7', 'black', 'Blueberry'),
	('1c1cf0', 'white', 'Bluebonnet'),
	('de5d83', 'black', 'Blush'),
	('79443b', 'white', 'Bole'),
	('0095b6', 'black', 'Bondi Blue'),
	('e3dac9', 'black', 'Bone'),
	('cc0000', 'white', 'Boston University Red'),
	('006a4e', 'white', 'Bangladesh Green'),
	('873260', 'white', 'Boysenberry'),
	('0070ff', 'white', 'Brandeis Blue'),
	('b5a642', 'black', 'Brass'),
	('cb4154', 'white', 'Brick Red'),
	('1dacd6', 'black', 'Bright Cerulean'),
	('66ff00', 'black', 'Bright Green'),
	('bf94e4', 'black', 'Bright Lavender'),
	('d891ef', 'black', 'Bright Lilac'),
	('c32148', 'white', 'Bright Maroon'),
	('1974d2', 'white', 'Bright Navy Blue'),
	('ff007f', 'white', 'Bright Pink'),
	('08e8de', 'black', 'Bright Turquoise'),
	('d19fe8', 'black', 'Bright Ube'),
	('f4bbff', 'black', 'Brilliant Lavender'),
	('ff55a3', 'black', 'Brilliant Rose'),
	('fb607f', 'black', 'Brink Pink'),
	('004225', 'white', 'British Racing Green'),
	('122e18', 'white', 'British Racing Green II Metalic'),
	('cd7f32', 'black', 'Bronze'),
	('737000', 'white', 'Bronze Yellow'),
	('964b00', 'white', 'Brown'),
	('a52a2a', 'white', 'Auburn'),
	('6b4423', 'white', 'Brown-Nose'),
	('1b4d3e', 'white', 'Brunswick Green'),
	('ffc1cc', 'black', 'Bubble Gum'),
	('e7feff', 'black', 'Bubbles'),
	('7bb661', 'black', 'Bud Green'),
	('f0dc82', 'black', 'Buff'),
	('480607', 'white', 'Bulgarian Rose'),
	('800020', 'white', 'Burgundy'),
	('deb887', 'black', 'Burlywood'),
	('cc5500', 'white', 'Burnt Orange'),
	('e97451', 'black', 'Burnt Sienna'),
	('8a3324', 'white', 'Burnt Umber'),
	('bd33a4', 'white', 'Byzantine'),
	('702963', 'white', 'Byzantium'),
	('007aa5', 'white', 'CG Blue'),
	('e03c31', 'white', 'CG Red'),
	('536872', 'white', 'Cadet'),
	('5f9ea0', 'black', 'Cadet Blue'),
	('91a3b0', 'black', 'Cadet Grey'),
	('006b3c', 'white', 'Cadmium Green'),
	('ed872d', 'black', 'Cadmium Orange'),
	('e30022', 'white', 'Cadmium Red'),
	('fff600', 'black', 'Cadmium Yellow'),
	('1e4d2b', 'white', 'Cal Poly Green'),
	('a3c1ad', 'black', 'Cambridge Blue'),
	('c19a6b', 'black', 'Camel'),
	('efbbcc', 'black', 'Cameo Pink'),
	('78866b', 'white', 'Camouflage Green'),
	('ffef00', 'black', 'Canary Yellow'),
	('ff0800', 'white', 'Candy Apple Red'),
	('e4717a', 'black', 'Candy Pink'),
	('00bfff', 'black', 'Capri'),
	('592720', 'white', 'Caput Mortuum'),
	('c41e3a', 'white', 'Cardinal'),
	('00cc99', 'black', 'Caribbean Green'),
	('960018', 'white', 'Carmine'),
	('d70040', 'white', 'Carmine'),
	('eb4c42', 'black', 'Carmine Pink'),
	('ff0038', 'white', 'Carmine Red'),
	('ffa6c9', 'black', 'Carnation Pink'),
	('b31b1b', 'white', 'Carnelian'),
	('99badd', 'black', 'Carolina Blue'),
	('ed9121', 'black', 'Carrot Orange'),
	('00563f', 'white', 'Castleton Green'),
	('062a78', 'white', 'Catalina Blue'),
	('703642', 'white', 'Catawba'),
	('c95a49', 'white', 'Cedar Chest'),
	('92a1cf', 'black', 'Ceil'),
	('ace1af', 'black', 'Celadon'),
	('007ba7', 'white', 'Celadon Blue'),
	('2f847c', 'white', 'Celadon Green'),
	('b2ffff', 'black', 'Celeste'),
	('4997d0', 'black', 'Celestial Blue'),
	('de3163', 'white', 'Cerise'),
	('ec3b83', 'black', 'Cerise Pink'),
	('007ba7', 'white', 'Celadon Blue'),
	('2a52be', 'white', 'Cerulean Blue'),
	('6d9bc3', 'black', 'Cerulean Frost'),
	('a0785a', 'white', 'Chamoisee'),
	('f7e7ce', 'black', 'Champagne'),
	('36454f', 'white', 'Charcoal'),
	('232b2b', 'white', 'Charleston Green'),
	('e68fac', 'black', 'Charm Pink'),
	('dfff00', 'black', 'Chartreuse'),
	('7fff00', 'black', 'Chartreuse'),
	('de3163', 'white', 'Cerise'),
	('ffb7c5', 'black', 'Cherry Blossom Pink'),
	('cd5c5c', 'white', 'Chestnut'),
	('de6fa1', 'black', 'China Pink'),
	('a8516e', 'white', 'China Rose'),
	('aa381e', 'white', 'Chinese Red'),
	('856088', 'white', 'Chinese Violet'),
	('7b3f00', 'white', 'Chocolate'),
	('d2691e', 'black', 'Chocolate'),
	('ffa700', 'black', 'Chrome Yellow'),
	('98817b', 'black', 'Cinereous'),
	('e34234', 'white', 'Cinnabar'),
	('d2691e', 'black', 'Chocolate'),
	('e4d00a', 'black', 'Citrine'),
	('9fa91f', 'black', 'Citron'),
	('7f1734', 'white', 'Claret'),
	('fbcce7', 'black', 'Classic Rose'),
	('0047ab', 'white', 'Cobalt'),
	('fe001a', 'white', 'Coca-cola Red'),
	('d2691e', 'black', 'Chocolate'),
	('965a3e', 'white', 'Coconut'),
	('6f4e37', 'white', 'Coffee'),
	('9bddff', 'black', 'Columbia Blue'),
	('f88379', 'black', 'Congo Pink'),
	('002e63', 'white', 'Cool Black'),
	('8c92ac', 'black', 'Cool Grey'),
	('b87333', 'black', 'Copper'),
	('da8a67', 'black', 'Copper'),
	('ad6f69', 'white', 'Copper Penny'),
	('cb6d51', 'black', 'Copper Red'),
	('996666', 'white', 'Copper Rose'),
	('ff3800', 'black', 'Coquelicot'),
	('ff7f50', 'black', 'Coral'),
	('f88379', 'black', 'Congo Pink'),
	('ff4040', 'black', 'Coral Red'),
	('893f45', 'white', 'Cordovan'),
	('fbec5d', 'black', 'Corn'),
	('b31b1b', 'white', 'Carnelian'),
	('6495ed', 'black', 'Cornflower Blue'),
	('fff8dc', 'black', 'Cornsilk'),
	('fff8e7', 'black', 'Cosmic Latte'),
	('ffbcd9', 'black', 'Cotton Candy'),
	('fffdd0', 'black', 'Cream'),
	('dc143c', 'white', 'Crimson'),
	('be0032', 'white', 'Crimson Glory'),
	('00ffff', 'black', 'Aqua'),
	('00b7eb', 'black', 'Cyan'),
	('58427c', 'white', 'Cyber Grape'),
	('ffd300', 'black', 'Cyber Yellow'),
	('ffff31', 'black', 'Daffodil'),
	('f0e130', 'black', 'Dandelion'),
	('00008b', 'white', 'Dark Blue'),
	('666699', 'white', 'Dark Blue-Gray'),
	('654321', 'white', 'Dark Brown'),
	('5d3954', 'white', 'Dark Byzantium'),
	('a40000', 'white', 'Dark Candy Apple Red'),
	('08457e', 'white', 'Dark Cerulean'),
	('986960', 'white', 'Dark Chestnut'),
	('cd5b45', 'white', 'Dark Coral'),
	('008b8b', 'white', 'Dark Cyan'),
	('536878', 'white', 'Dark Electric Blue'),
	('b8860b', 'black', 'Dark Goldenrod'),
	('a9a9a9', 'black', 'Dark Gray'),
	('013220', 'white', 'Dark Green'),
	('00416a', 'white', 'Dark Imperial Blue'),
	('1a2421', 'white', 'Dark Jungle Green'),
	('bdb76b', 'black', 'Dark Khaki'),
	('483c32', 'white', 'Dark Lava'),
	('734f96', 'white', 'Dark Lavender'),
	('534b4f', 'white', 'Dark Liver'),
	('543d37', 'white', 'Dark Liver'),
	('8b008b', 'white', 'Dark Magenta'),
	('003366', 'white', 'Dark Midnight Blue'),
	('4a5d23', 'white', 'Dark Moss Green'),
	('556b2f', 'white', 'Dark Olive Green'),
	('ff8c00', 'black', 'Dark Orange'),
	('9932cc', 'white', 'Dark Orchid'),
	('779ecb', 'black', 'Dark Pastel Blue'),
	('03c03c', 'black', 'Dark Pastel Green'),
	('966fd6', 'black', 'Dark Pastel Purple'),
	('c23b22', 'white', 'Dark Pastel Red'),
	('e75480', 'black', 'Dark Pink'),
	('003399', 'white', 'Dark Powder Blue'),
	('4f3a3c', 'white', 'Dark Puce'),
	('872657', 'white', 'Dark Raspberry'),
	('8b0000', 'white', 'Dark Red'),
	('e9967a', 'black', 'Dark Salmon'),
	('560319', 'white', 'Dark Scarlet'),
	('8fbc8f', 'black', 'Dark Sea Green'),
	('3c1414', 'white', 'Dark Sienna'),
	('8cbed6', 'black', 'Dark Sky Blue'),
	('483d8b', 'white', 'Dark Slate Blue'),
	('2f4f4f', 'white', 'Dark Slate Gray'),
	('177245', 'white', 'Dark Spring Green'),
	('918151', 'black', 'Dark Tan'),
	('ffa812', 'black', 'Dark Tangerine'),
	('483c32', 'white', 'Dark Lava'),
	('cc4e5c', 'white', 'Dark Terra Cotta'),
	('00ced1', 'black', 'Dark Turquoise'),
	('d1bea8', 'black', 'Dark Vanilla'),
	('9400d3', 'white', 'Dark Violet'),
	('9b870c', 'black', 'Dark Yellow'),
	('00703c', 'white', 'Dartmouth Green'),
	('555555', 'white', "Davy's Grey"),
	('d70a53', 'white', 'Debian Red'),
	('a9203e', 'white', 'Deep Carmine'),
	('ef3038', 'white', 'Deep Carmine Pink'),
	('e9692c', 'black', 'Deep Carrot Orange'),
	('da3287', 'white', 'Deep Cerise'),
	('fad6a5', 'black', 'Deep Champagne'),
	('b94e48', 'white', 'Deep Chestnut'),
	('704241', 'white', 'Deep Coffee'),
	('c154c1', 'white', 'Deep Fuchsia'),
	('004b49', 'white', 'Deep Jungle Green'),
	('f5c71a', 'black', 'Deep Lemon'),
	('9955bb', 'white', 'Deep Lilac'),
	('cc00cc', 'white', 'Deep Magenta'),
	('d473d4', 'black', 'Deep Mauve'),
	('355e3b', 'white', 'Deep Moss Green'),
	('ffcba4', 'black', 'Deep Peach'),
	('ff1493', 'black', 'Deep Pink'),
	('a95c68', 'white', 'Deep Puce'),
	('843f5b', 'white', 'Deep Ruby'),
	('ff9933', 'black', 'Deep Saffron'),
	('00bfff', 'black', 'Capri'),
	('4a646c', 'white', 'Deep Space Sparkle'),
	('7e5e60', 'white', 'Deep Taupe'),
	('66424d', 'white', 'Deep Tuscan Red'),
	('ba8759', 'black', 'Deer'),
	('1560bd', 'white', 'Denim'),
	('c19a6b', 'black', 'Camel'),
	('edc9af', 'black', 'Desert Sand'),
	('ea3c53', 'white', 'Desire'),
	('b9f2ff', 'black', 'Diamond'),
	('696969', 'white', 'Dim Gray'),
	('9b7653', 'white', 'Dirt'),
	('1e90ff', 'black', 'Dodger Blue'),
	('d71868', 'white', 'Dogwood Rose'),
	('85bb65', 'black', 'Dollar Bill'),
	('664c28', 'white', 'Donkey Brown'),
	('967117', 'white', 'Bistre Brown'),
	('00009c', 'white', 'Duke Blue'),
	('e5ccc9', 'black', 'Dust Storm'),
	('efdfbb', 'black', 'Dutch White'),
	('004953', 'white', 'Eagle Green'),
	('e1a95f', 'black', 'Earth Yellow'),
	('555d50', 'white', 'Ebony'),
	('c2b280', 'black', 'Ecru'),
	('1b1b1b', 'white', 'Eerie Black'),
	('614051', 'white', 'Eggplant'),
	('f0ead6', 'black', 'Eggshell'),
	('1034a6', 'white', 'Egyptian Blue'),
	('7df9ff', 'black', 'Electric Blue'),
	('ff003f', 'white', 'Electric Crimson'),
	('00ffff', 'black', 'Aqua'),
	('00ff00', 'black', 'Electric Green'),
	('6f00ff', 'white', 'Electric Indigo'),
	('f4bbff', 'black', 'Brilliant Lavender'),
	('ccff00', 'black', 'Electric Lime'),
	('bf00ff', 'white', 'Electric Purple'),
	('3f00ff', 'white', 'Electric Ultramarine'),
	('8f00ff', 'white', 'Electric Violet'),
	('ffff00', 'black', 'Electric Yellow'),
	('50c878', 'black', 'Emerald'),
	('6c3082', 'white', 'Eminence'),
	('1b4d3e', 'white', 'Brunswick Green'),
	('b48395', 'black', 'English Lavender'),
	('ab4b52', 'white', 'English Red'),
	('563c5c', 'white', 'English Violet'),
	('96c8a2', 'black', 'Eton Blue'),
	('44d7a8', 'black', 'Eucalyptus'),
	('3b5998', 'white', 'Facebook Blue'),
	('c19a6b', 'black', 'Camel'),
	('801818', 'white', 'Falu Red'),
	('b53389', 'white', 'Fandango'),
	('de5285', 'black', 'Fandango Pink'),
	('f400a1', 'white', 'Fashion Fuchsia'),
	('e5aa70', 'black', 'Fawn'),
	('4d5d53', 'white', 'Feldgrau'),
	('fdd5b1', 'black', 'Feldspar'),
	('4f7942', 'white', 'Fern Green'),
	('ff2800', 'white', 'Ferrari Red'),
	('6c541e', 'white', 'Field Drab'),
	('ce2029', 'white', 'Fire Engine Red'),
	('b22222', 'white', 'Firebrick'),
	('e25822', 'black', 'Flame'),
	('fc8eac', 'black', 'Flamingo Pink'),
	('6b4423', 'white', 'Brown-Nose'),
	('f7e98e', 'black', 'Flavescent'),
	('eedc82', 'black', 'Flax'),
	('a2006d', 'white', 'Flirt'),
	('fffaf0', 'black', 'Floral White'),
	('ffbf00', 'black', 'Amber'),
	('ff1493', 'black', 'Deep Pink'),
	('ccff00', 'black', 'Electric Lime'),
	('ff004f', 'white', 'Folly'),
	('014421', 'white', 'Forest Green'),
	('228b22', 'white', 'Forest Green'),
	('856d4d', 'white', 'French Bistre'),
	('0072bb', 'white', 'French Blue'),
	('fd3f92', 'black', 'French Fuchsia'),
	('86608e', 'white', 'French Lilac'),
	('ccff00', 'black', 'Electric Lime'),
	('d473d4', 'black', 'Deep Mauve'),
	('fd6c9e', 'black', 'French Pink'),
	('4e1609', 'white', 'French Puce'),
	('c72c48', 'white', 'French Raspberry'),
	('f64a8a', 'black', 'French Rose'),
	('77b5fe', 'black', 'French Sky Blue'),
	('8806ce', 'white', 'French Violet'),
	('ac1e44', 'white', 'French Wine'),
	('a6e7ff', 'black', 'Fresh Air'),
	('ff00ff', 'black', 'Fuchsia'),
	('c154c1', 'white', 'Deep Fuchsia'),
	('ff77ff', 'black', 'Fuchsia Pink'),
	('cc397b', 'white', 'Fuchsia Purple'),
	('c74375', 'white', 'Fuchsia Rose'),
	('e48400', 'black', 'Fulvous'),
	('cc6666', 'black', 'Fuzzy Wuzzy'),
	('00ab66', 'black', 'GO Green'),
	('3369e8', 'white', 'Google blue'),
	('d50f25', 'white', 'Google red'),
	('eeb211', 'black', 'Google yellow'),
	('009925', 'white', 'Google green'),
	('dcdcdc', 'black', 'Gainsboro'),
	('e49b0f', 'black', 'Gamboge'),
	('007f66', 'white', 'Generic Viridian'),
	('f8f8ff', 'black', 'Ghost White'),
	('fe5a1d', 'black', 'Giants Orange'),
	('b06500', 'white', 'Ginger'),
	('6082b6', 'white', 'Glaucous'),
	('e6e8fa', 'black', 'Glitter'),
	('d4af37', 'black', 'Gold'),
	('ffd700', 'black', 'Gold'),
	('85754e', 'white', 'Gold Fusion'),
	('996515', 'white', 'Golden Brown'),
	('fcc200', 'black', 'Golden Poppy'),
	('ffdf00', 'black', 'Golden Yellow'),
	('daa520', 'black', 'Goldenrod'),
	('a8e4a0', 'black', 'Granny Smith Apple'),
	('6f2da8', 'white', 'Grape'),
	('808080', 'white', 'Gray'),
	('808080', 'white', 'Gray'),
	('808080', 'white', 'Gray'),
	('bebebe', 'black', 'Gray'),
	('8c92ac', 'black', 'Cool Grey'),
	('465945', 'white', 'Gray-asparagus'),
	('00ff00', 'black', 'Electric Green'),
	('1cac78', 'black', 'Green'),
	('008000', 'white', 'Ao'),
	('00a877', 'black', 'Green'),
	('009f6b', 'black', 'Green'),
	('66b032', 'black', 'Green'),
	('00a550', 'black', 'Green'),
	('adff2f', 'black', 'Green-yellow'),
	('a99a86', 'black', 'Grullo'),
	('00ff7f', 'black', 'Guppie Green'),
	('446ccf', 'white', 'Han Blue'),
	('5218fa', 'white', 'Han Purple'),
	('e9d66b', 'black', 'Arylide Yellow'),
	('3fff00', 'black', 'Harlequin'),
	('c90016', 'white', 'Harvard Crimson'),
	('da9100', 'black', 'Harvest Gold'),
	('808000', 'white', 'Heart Gold'),
	('df73ff', 'black', 'Heliotrope'),
	('aa98a9', 'black', 'Heliotrope Gray'),
	('f400a1', 'white', 'Fashion Fuchsia'),
	('f0fff0', 'black', 'Honeydew'),
	('007fbf', 'white', 'Honolulu Blue'),
	('49796b', 'white', "Hooker's Green"),
	('ff1dce', 'black', 'Hot Magenta'),
	('ff69b4', 'black', 'Hot Pink'),
	('355e3b', 'white', 'Deep Moss Green'),
	('71a6d2', 'black', 'Iceberg'),
	('fcf75e', 'black', 'Icterine'),
	('319177', 'white', 'Illuminating Emerald'),
	('602ffb', 'white', 'Imperial'),
	('002395', 'white', 'Imperial Blue'),
	('66023c', 'white', 'Imperial Purple'),
	('ed2939', 'white', 'Imperial Red'),
	('b2ec5d', 'black', 'Inchworm'),
	('4c516d', 'white', 'Independence'),
	('138808', 'white', 'India Green'),
	('cd5c5c', 'white', 'Chestnut'),
	('e3a857', 'black', 'Indian Yellow'),
	('6f00ff', 'white', 'Electric Indigo'),
	('00416a', 'white', 'Dark Imperial Blue'),
	('4b0082', 'white', 'Indigo'),
	('091f92', 'white', 'Indigo Dye'),
	('002fa7', 'white', 'International Klein Blue'),
	('ba160c', 'white', 'International Orange'),
	('c0362c', 'white', 'International Orange'),
	('ff4f00', 'black', 'International Orange'),
	('5a4fcf', 'white', 'Iris'),
	('b3446c', 'white', 'Irresistible'),
	('f4f0ec', 'black', 'Isabelline'),
	('009000', 'white', 'Islamic Green'),
	('b2ffff', 'black', 'Celeste'),
	('fffff0', 'black', 'Ivory'),
	('00a86b', 'black', 'Jade'),
	('9d2933', 'white', 'Japanese Carmine'),
	('264348', 'white', 'Japanese Indigo'),
	('5b3256', 'white', 'Japanese Violet'),
	('f8de7e', 'black', 'Jasmine'),
	('d73b3e', 'white', 'Jasper'),
	('a50b5e', 'white', 'Jazzberry Jam'),
	('da614e', 'black', 'Jelly Bean'),
	('343434', 'white', 'Jet'),
	('fada5e', 'black', 'Jonquil'),
	('8ab9f1', 'black', 'Jordy Blue'),
	('bdda57', 'black', 'June Bud'),
	('29ab87', 'black', 'Jungle Green'),
	('e8000d', 'white', 'KU Crimson'),
	('4cbb17', 'black', 'Kelly Green'),
	('7c1c05', 'white', 'Kenyan Copper'),
	('3ab09e', 'black', 'Keppel'),
	('c3b091', 'black', 'Khaki'),
	('f0e68c', 'black', 'Khaki'),
	('882d17', 'white', 'Kobe'),
	('e79fc4', 'black', 'Kobi'),
	('354230', 'white', 'Kombu Green'),
	('087830', 'white', 'La Salle Green'),
	('d6cadd', 'black', 'Languid Lavender'),
	('26619c', 'white', 'Lapis Lazuli'),
	('fefe22', 'black', 'Laser Lemon'),
	('a9ba9d', 'black', 'Laurel Green'),
	('cf1020', 'white', 'Lava'),
	('e6e6fa', 'black', 'Lavender'),
	('b57edc', 'black', 'Lavender'),
	('ccccff', 'black', 'Lavender Blue'),
	('fff0f5', 'black', 'Lavender Blush'),
	('c4c3d0', 'black', 'Lavender Gray'),
	('9457eb', 'white', 'Lavender Indigo'),
	('ee82ee', 'black', 'Lavender Magenta'),
	('e6e6fa', 'black', 'Lavender'),
	('fbaed2', 'black', 'Lavender Pink'),
	('967bb6', 'black', 'Lavender Purple'),
	('fba0e3', 'black', 'Lavender Rose'),
	('7cfc00', 'black', 'Lawn Green'),
	('fff700', 'black', 'Lemon'),
	('fffacd', 'black', 'Lemon Chiffon'),
	('cca01d', 'black', 'Lemon Curry'),
	('fdff00', 'black', 'Lemon Glacier'),
	('e3ff00', 'black', 'Lemon Lime'),
	('f6eabe', 'black', 'Lemon Meringue'),
	('fff44f', 'black', 'Lemon Yellow'),
	('545aa7', 'white', 'Liberty'),
	('1a1110', 'white', 'Licorice'),
	('fdd5b1', 'black', 'Feldspar'),
	('add8e6', 'black', 'Light Blue'),
	('b5651d', 'white', 'Light Brown'),
	('e66771', 'black', 'Light Carmine Pink'),
	('f08080', 'black', 'Light Coral'),
	('93ccea', 'black', 'Light Cornflower Blue'),
	('f56991', 'black', 'Light Crimson'),
	('e0ffff', 'black', 'Light Cyan'),
	('ff5ccd', 'black', 'Light Deep Pink'),
	('c8ad7f', 'black', 'Light French Beige'),
	('f984ef', 'black', 'Light Fuchsia Pink'),
	('fafad2', 'black', 'Light Goldenrod Yellow'),
	('d3d3d3', 'black', 'Light Gray'),
	('90ee90', 'black', 'Light Green'),
	('ffb3de', 'black', 'Light Hot Pink'),
	('f0e68c', 'black', 'Khaki'),
	('d39bcb', 'black', 'Light Medium Orchid'),
	('addfad', 'black', 'Light Moss Green'),
	('e6a8d7', 'black', 'Light Orchid'),
	('b19cd9', 'black', 'Light Pastel Purple'),
	('ffb6c1', 'black', 'Light Pink'),
	('e97451', 'black', 'Burnt Sienna'),
	('ffa07a', 'black', 'Light Salmon'),
	('ff9999', 'black', 'Light Salmon Pink'),
	('20b2aa', 'black', 'Light Sea Green'),
	('87cefa', 'black', 'Light Sky Blue'),
	('778899', 'black', 'Light Slate Gray'),
	('b0c4de', 'black', 'Light Steel Blue'),
	('b38b6d', 'black', 'Light Taupe'),
	('e68fac', 'black', 'Charm Pink'),
	('ffffe0', 'black', 'Light Yellow'),
	('c8a2c8', 'black', 'Lilac'),
	('bfff00', 'black', 'Lime'),
	('00ff00', 'black', 'Electric Green'),
	('32cd32', 'black', 'Lime Green'),
	('9dc209', 'black', 'Limerick'),
	('195905', 'white', 'Lincoln Green'),
	('faf0e6', 'black', 'Linen'),
	('c19a6b', 'black', 'Camel'),
	('de6fa1', 'black', 'China Pink'),
	('6ca0dc', 'black', 'Little Boy Blue'),
	('534b4f', 'white', 'Dark Liver'),
	('b86d29', 'white', 'Liver'),
	('6c2e1f', 'white', 'Liver'),
	('987456', 'white', 'Liver Chestnut'),
	('6699cc', 'black', 'Blue-gray'),
	('ffe4cd', 'black', 'Lumber'),
	('e62020', 'white', 'Lust'),
	('18453b', 'white', 'MSU Green'),
	('ff00ff', 'black', 'Fuchsia'),
	('ff55a3', 'black', 'Brilliant Rose'),
	('d0417e', 'white', 'Magenta'),
	('ca1f7b', 'white', 'Magenta'),
	('ff0090', 'black', 'Magenta'),
	('9f4576', 'white', 'Magenta Haze'),
	('aaf0d1', 'black', 'Magic Mint'),
	('f8f4ff', 'black', 'Magnolia'),
	('c04000', 'white', 'Mahogany'),
	('fbec5d', 'black', 'Corn'),
	('6050dc', 'white', 'Majorelle Blue'),
	('0bda51', 'black', 'Malachite'),
	('979aaa', 'black', 'Manatee'),
	('ff8243', 'black', 'Mango Tango'),
	('74c365', 'black', 'Mantis'),
	('880085', 'white', 'Mardi Gras'),
	('800000', 'white', 'Maroon'),
	('c32148', 'white', 'Bright Maroon'),
	('800000', 'white', 'Maroon'),
	('b03060', 'white', 'Maroon'),
	('e0b0ff', 'black', 'Mauve'),
	('915f6d', 'white', 'Mauve Taupe'),
	('ef98aa', 'black', 'Mauvelous'),
	('4c9141', 'white', 'May Green'),
	('73c2fb', 'black', 'Maya Blue'),
	('e5b73b', 'black', 'Meat Brown'),
	('66ddaa', 'black', 'Medium Aquamarine'),
	('0000cd', 'white', 'Medium Blue'),
	('e2062c', 'white', 'Medium Candy Apple Red'),
	('af4035', 'white', 'Medium Carmine'),
	('f3e5ab', 'black', 'Medium Champagne'),
	('035096', 'white', 'Medium Electric Blue'),
	('1c352d', 'white', 'Medium Jungle Green'),
	('dda0dd', 'black', 'Medium Lavender Magenta'),
	('ba55d3', 'white', 'Medium Orchid'),
	('0067a5', 'white', 'Medium Persian Blue'),
	('9370db', 'black', 'Medium Purple'),
	('bb3385', 'white', 'Medium Red-violet'),
	('aa4069', 'white', 'Medium Ruby'),
	('3cb371', 'black', 'Medium Sea Green'),
	('80daeb', 'black', 'Medium Sky Blue'),
	('7b68ee', 'white', 'Medium Slate Blue'),
	('c9dc87', 'black', 'Medium Spring Bud'),
	('00fa9a', 'black', 'Medium Spring Green'),
	('674c47', 'white', 'Medium Taupe'),
	('48d1cc', 'black', 'Medium Turquoise'),
	('79443b', 'white', 'Bole'),
	('d9603b', 'black', 'Medium Vermilion'),
	('c71585', 'white', 'Medium Violet-red'),
	('f8b878', 'black', 'Mellow Apricot'),
	('f8de7e', 'black', 'Jasmine'),
	('fdbcb4', 'black', 'Melon'),
	('0a7e8c', 'white', 'Metallic Seaweed'),
	('9c7c38', 'white', 'Metallic Sunburst'),
	('e4007c', 'white', 'Mexican Pink'),
	('191970', 'white', 'Midnight Blue'),
	('004953', 'white', 'Eagle Green'),
	('e3f988', 'black', 'Midori'),
	('ffc40c', 'black', 'Mikado Yellow'),
	('e3f988', 'black', 'Midori'),
	('3eb489', 'black', 'Mint'),
	('f5fffa', 'black', 'Mint Cream'),
	('98ff98', 'black', 'Mint Green'),
	('ffe4e1', 'black', 'Misty Rose'),
	('faebd7', 'black', 'Antique White'),
	('967117', 'white', 'Bistre Brown'),
	('73a9c2', 'black', 'Moonstone Blue'),
	('ae0c00', 'white', 'Mordant Red 19'),
	('addfad', 'black', 'Light Moss Green'),
	('30ba8f', 'black', 'Mountain Meadow'),
	('997a8d', 'black', 'Mountbatten Pink'),
	('306030', 'white', 'Mughal Green'),
	('c54b8c', 'white', 'Mulberry'),
	('ffdb58', 'black', 'Mustard'),
	('21421e', 'white', 'Myrtle'),
	('317873', 'white', 'Myrtle Green'),
	('f6adc6', 'black', 'Nadeshiko Pink'),
	('2a8000', 'white', 'Napier Green'),
	('fada5e', 'black', 'Jonquil'),
	('ffdead', 'black', 'Navajo White'),
	('000080', 'white', 'Navy'),
	('000080', 'white', 'Navy'),
	('9457eb', 'white', 'Lavender Indigo'),
	('ffa343', 'black', 'Neon Carrot'),
	('fe4164', 'black', 'Neon Fuchsia'),
	('39ff14', 'black', 'Neon Green'),
	('214fc6', 'white', 'New Car'),
	('d7837f', 'black', 'New York Pink'),
	('a4dded', 'black', 'Non-photo Blue'),
	('059033', 'white', 'North Texas Green'),
	('e9ffdb', 'black', 'Nyanza'),
	('990000', 'white', 'OU Crimson Red'),
	('0077be', 'white', 'Ocean Boat Blue'),
	('cc7722', 'black', 'Ochre'),
	('008000', 'white', 'Ao'),
	('43302e', 'white', 'Old Burgundy'),
	('cfb53b', 'black', 'Old Gold'),
	('563c5c', 'white', 'English Violet'),
	('fdf5e6', 'black', 'Old Lace'),
	('796878', 'white', 'Old Lavender'),
	('673147', 'white', 'Old Mauve'),
	('867e36', 'white', 'Old Moss Green'),
	('c08081', 'black', 'Old Rose'),
	('848482', 'black', 'Battleship Grey'),
	('808000', 'white', 'Heart Gold'),
	('3c341f', 'white', 'Olive Drab #7'),
	('6b8e23', 'white', 'Olive Drab'),
	('9ab973', 'black', 'Olivine'),
	('353839', 'white', 'Onyx'),
	('b784a7', 'black', 'Opera Mauve'),
	('ff7f00', 'black', 'Orange'),
	('ff7538', 'black', 'Orange'),
	('ff5800', 'black', 'Orange'),
	('fb9902', 'black', 'Orange'),
	('ffa500', 'black', 'Orange'),
	('ff9f00', 'black', 'Orange Peel'),
	('ff4500', 'black', 'Orange-red'),
	('da70d6', 'black', 'Orchid'),
	('f2bdcd', 'black', 'Orchid Pink'),
	('fb4f14', 'black', 'Orioles Orange'),
	('654321', 'white', 'Dark Brown'),
	('414a4c', 'white', 'Outer Space'),
	('ff6e4a', 'black', 'Outrageous Orange'),
	('002147', 'white', 'Oxford Blue'),
	('006600', 'white', 'Pakistan Green'),
	('273be2', 'white', 'Palatinate Blue'),
	('682860', 'white', 'Palatinate Purple'),
	('bcd4e6', 'black', 'Beau Blue'),
	('afeeee', 'black', 'Pale Blue'),
	('987654', 'white', 'Pale Brown'),
	('af4035', 'white', 'Medium Carmine'),
	('9bc4e2', 'black', 'Pale Cerulean'),
	('ddadaf', 'black', 'Pale Chestnut'),
	('da8a67', 'black', 'Copper'),
	('abcdef', 'black', 'Pale Cornflower Blue'),
	('e6be8a', 'black', 'Pale Gold'),
	('eee8aa', 'black', 'Pale Goldenrod'),
	('98fb98', 'black', 'Pale Green'),
	('dcd0ff', 'black', 'Pale Lavender'),
	('f984e5', 'black', 'Pale Magenta'),
	('fadadd', 'black', 'Pale Pink'),
	('dda0dd', 'black', 'Medium Lavender Magenta'),
	('db7093', 'black', 'Pale Red-violet'),
	('96ded1', 'black', 'Pale Robin Egg Blue'),
	('c9c0bb', 'black', 'Pale Silver'),
	('ecebbd', 'black', 'Pale Spring Bud'),
	('bc987e', 'black', 'Pale Taupe'),
	('afeeee', 'black', 'Pale Blue'),
	('db7093', 'black', 'Pale Red-violet'),
	('78184a', 'white', 'Pansy Purple'),
	('009b7d', 'black', 'Paolo Veronese Green'),
	('ffefd5', 'black', 'Papaya Whip'),
	('e63e62', 'white', 'Paradise Pink'),
	('50c878', 'black', 'Emerald'),
	('aec6cf', 'black', 'Pastel Blue'),
	('836953', 'white', 'Pastel Brown'),
	('cfcfc4', 'black', 'Pastel Gray'),
	('77dd77', 'black', 'Pastel Green'),
	('f49ac2', 'black', 'Pastel Magenta'),
	('ffb347', 'black', 'Pastel Orange'),
	('dea5a4', 'black', 'Pastel Pink'),
	('b39eb5', 'black', 'Pastel Purple'),
	('ff6961', 'black', 'Pastel Red'),
	('cb99c9', 'black', 'Pastel Violet'),
	('fdfd96', 'black', 'Pastel Yellow'),
	('800080', 'white', 'Patriarch'),
	('536878', 'white', 'Dark Electric Blue'),
	('ffe5b4', 'black', 'Peach'),
	('ffcba4', 'black', 'Deep Peach'),
	('ffdab9', 'black', 'Peach Puff'),
	('ffcc99', 'black', 'Peach-orange'),
	('fadfad', 'black', 'Peach-yellow'),
	('d1e231', 'black', 'Pear'),
	('eae0c8', 'black', 'Pearl'),
	('88d8c0', 'black', 'Pearl Aqua'),
	('b768a2', 'black', 'Pearly Purple'),
	('e6e200', 'black', 'Peridot'),
	('ccccff', 'black', 'Lavender Blue'),
	('1c39bb', 'white', 'Persian Blue'),
	('00a693', 'black', 'Persian Green'),
	('32127a', 'white', 'Persian Indigo'),
	('d99058', 'black', 'Persian Orange'),
	('f77fbe', 'black', 'Persian Pink'),
	('701c1c', 'white', 'Persian Plum'),
	('cc3333', 'white', 'Persian Red'),
	('fe28a2', 'black', 'Persian Rose'),
	('ec5800', 'black', 'Persimmon'),
	('cd853f', 'black', 'Peru'),
	('df00ff', 'white', 'Phlox'),
	('000f89', 'white', 'Phthalo Blue'),
	('123524', 'white', 'Phthalo Green'),
	('45b1e8', 'black', 'Picton Blue'),
	('c30b4e', 'white', 'Pictorial Carmine'),
	('fddde6', 'black', 'Piggy Pink'),
	('01796f', 'white', 'Pine Green'),
	('ffc0cb', 'black', 'Pink'),
	('d74894', 'white', 'Pink'),
	('ffddf4', 'black', 'Pink Lace'),
	('d8b2d1', 'black', 'Pink Lavender'),
	('e7accf', 'black', 'Pink Pearl'),
	('f78fa7', 'black', 'Pink Sherbet'),
	('ff9966', 'black', 'Atomic Tangerine'),
	('93c572', 'black', 'Pistachio'),
	('e5e4e2', 'black', 'Platinum'),
	('8e4585', 'white', 'Plum'),
	('dda0dd', 'black', 'Medium Lavender Magenta'),
	('86608e', 'white', 'French Lilac'),
	('be4f62', 'white', 'Popstar'),
	('ff5a36', 'black', 'Portland Orange'),
	('b0e0e6', 'black', 'Powder Blue'),
	('b0e0e6', 'black', 'Powder Blue'),
	('ff8f00', 'black', 'Princeton Orange'),
	('701c1c', 'white', 'Persian Plum'),
	('003153', 'white', 'Prussian Blue'),
	('df00ff', 'white', 'Phlox'),
	('cc8899', 'black', 'Puce'),
	('722f37', 'white', 'Puce Red'),
	('644117', 'white', 'Pullman Brown'),
	('ff7518', 'black', 'Pumpkin'),
	('800080', 'white', 'Patriarch'),
	('800080', 'white', 'Patriarch'),
	('9f00c5', 'white', 'Purple'),
	('a020f0', 'white', 'Purple'),
	('69359c', 'white', 'Purple Heart'),
	('9678b6', 'black', 'Purple Mountain Majesty'),
	('4e5180', 'white', 'Purple Navy'),
	('fe4eda', 'black', 'Purple Pizzazz'),
	('50404d', 'white', 'Purple Taupe'),
	('9a4eae', 'white', 'Purpureus'),
	('51484f', 'white', 'Quartz'),
	('436b95', 'white', 'Queen Blue'),
	('e8cc07', 'black', 'Queen Pink'),
	('8e3a59', 'white', 'Quinacridone Magenta'),
	('5d8aa8', 'black', 'Air Force Blue'),
	('ff355e', 'black', 'Radical Red'),
	('fbab60', 'black', 'Rajah'),
	('e30b5d', 'white', 'Raspberry'),
	('915f6d', 'white', 'Mauve Taupe'),
	('e25098', 'black', 'Raspberry Pink'),
	('b3446c', 'white', 'Irresistible'),
	('826644', 'white', 'Raw Umber'),
	('ff33cc', 'black', 'Razzle Dazzle Rose'),
	('e3256b', 'white', 'Razzmatazz'),
	('8d4e85', 'white', 'Razzmic Berry'),
	('ff0000', 'white', 'Red'),
	('ee204d', 'white', 'Red'),
	('f2003c', 'white', 'Red'),
	('c40233', 'white', 'Red'),
	('ed2939', 'white', 'Imperial Red'),
	('fe2712', 'white', 'Red'),
	('ed1c24', 'white', 'Red'),
	('860111', 'white', 'Red Devil'),
	('e40078', 'white', 'Red-Purple'),
	('a52a2a', 'white', 'Auburn'),
	('ff5349', 'black', 'Red-orange'),
	('c71585', 'white', 'Medium Violet-red'),
	('ab4e52', 'white', 'Redwood'),
	('522d80', 'white', 'Regalia'),
	('002387', 'white', 'Resolution Blue'),
	('777696', 'white', 'Rhythm'),
	('004040', 'white', 'Rich Black'),
	('f1a7fe', 'black', 'Rich Brilliant Lavender'),
	('d70040', 'white', 'Carmine'),
	('0892d0', 'black', 'Rich Electric Blue'),
	('a76bcf', 'black', 'Rich Lavender'),
	('b666d2', 'black', 'Rich Lilac'),
	('b03060', 'white', 'Maroon'),
	('414833', 'white', 'Rifle Green'),
	('704241', 'white', 'Deep Coffee'),
	('00cccc', 'black', 'Robin Egg Blue'),
	('8a7f80', 'white', 'Rocket Metallic'),
	('838996', 'black', 'Roman Silver'),
	('ff007f', 'white', 'Bright Pink'),
	('f9429e', 'black', 'Rose Bonbon'),
	('674846', 'white', 'Rose Ebony'),
	('b76e79', 'black', 'Rose Gold'),
	('e32636', 'white', 'Alizarin Crimson'),
	('ff66cc', 'black', 'Rose Pink'),
	('aa98a9', 'black', 'Heliotrope Gray'),
	('c21e56', 'white', 'Rose Red'),
	('905d5d', 'white', 'Rose Taupe'),
	('ab4e52', 'white', 'Redwood'),
	('65000b', 'white', 'Rosewood'),
	('d40000', 'white', 'Rosso Corsa'),
	('bc8f8f', 'black', 'Rosy Brown'),
	('0038a8', 'white', 'Royal Azure'),
	('002366', 'white', 'Royal Blue'),
	('4169e1', 'white', 'Royal Blue'),
	('ca2c92', 'white', 'Royal Fuchsia'),
	('7851a9', 'white', 'Royal Purple'),
	('fada5e', 'black', 'Jonquil'),
	('ce4676', 'white', 'Ruber'),
	('d10056', 'white', 'Rubine Red'),
	('e0115f', 'white', 'Ruby'),
	('9b111e', 'white', 'Ruby Red'),
	('ff0028', 'white', 'Ruddy'),
	('bb6528', 'white', 'Ruddy Brown'),
	('e18e96', 'black', 'Ruddy Pink'),
	('a81c07', 'white', 'Rufous'),
	('80461b', 'white', 'Russet'),
	('679267', 'black', 'Russian Green'),
	('32174d', 'white', 'Russian Violet'),
	('b7410e', 'white', 'Rust'),
	('da2c43', 'white', 'Rusty Red'),
	('ff7e00', 'black', 'Amber'),
	('00563f', 'white', 'Castleton Green'),
	('8b4513', 'white', 'Saddle Brown'),
	('ff6700', 'black', 'Safety Orange'),
	('eed202', 'black', 'Safety Yellow'),
	('f4c430', 'black', 'Saffron'),
	('bcb88a', 'black', 'Sage'),
	('ff8c69', 'black', 'Salmon'),
	('ff91a4', 'black', 'Salmon Pink'),
	('c2b280', 'black', 'Ecru'),
	('967117', 'white', 'Bistre Brown'),
	('ecd540', 'black', 'Sandstorm'),
	('f4a460', 'black', 'Sandy Brown'),
	('967117', 'white', 'Bistre Brown'),
	('92000a', 'white', 'Sangria'),
	('507d2a', 'white', 'Sap Green'),
	('0f52ba', 'white', 'Sapphire'),
	('0067a5', 'white', 'Medium Persian Blue'),
	('cba135', 'black', 'Satin Sheen Gold'),
	('ff2400', 'white', 'Scarlet'),
	('fd0e35', 'white', 'Scarlet'),
	('ff91af', 'black', 'Baker-Miller Pink'),
	('ffd800', 'black', 'School Bus Yellow'),
	('76ff7a', 'black', "Screamin' Green"),
	('006994', 'white', 'Sea Blue'),
	('2e8b57', 'white', 'Sea Green'),
	('321414', 'white', 'Seal Brown'),
	('fff5ee', 'black', 'Seashell'),
	('ffba00', 'black', 'Selective Yellow'),
	('704214', 'white', 'Sepia'),
	('8a795d', 'white', 'Shadow'),
	('778ba5', 'black', 'Shadow Blue'),
	('ffcff1', 'black', 'Shampoo'),
	('009e60', 'black', 'Shamrock Green'),
	('8fd400', 'black', 'Sheen Green'),
	('d98695', 'black', 'Shimmering Blush'),
	('fc0fc0', 'black', 'Shocking Pink'),
	('ff6fff', 'black', 'Shocking Pink'),
	('882d17', 'white', 'Kobe'),
	('c0c0c0', 'black', 'Silver'),
	('acacac', 'black', 'Silver Chalice'),
	('5d89ba', 'black', 'Silver Lake Blue'),
	('c4aead', 'black', 'Silver Pink'),
	('bfc1c2', 'black', 'Silver Sand'),
	('cb410b', 'white', 'Sinopia'),
	('007474', 'white', 'Skobeloff'),
	('87ceeb', 'black', 'Sky Blue'),
	('cf71af', 'black', 'Sky Magenta'),
	('6a5acd', 'white', 'Slate Blue'),
	('708090', 'white', 'Slate Gray'),
	('003399', 'white', 'Dark Powder Blue'),
	('c84186', 'white', 'Smitten'),
	('738276', 'white', 'Smoke'),
	('933d41', 'white', 'Smokey Topaz'),
	('100c08', 'white', 'Smoky Black'),
	('fffafa', 'black', 'Snow'),
	('cec8ef', 'black', 'Soap'),
	('893843', 'white', 'Solid Pink'),
	('757575', 'white', 'Sonic Silver'),
	('1d2951', 'white', 'Space Cadet'),
	('807532', 'white', 'Spanish Bistre'),
	('0070b8', 'white', 'Spanish Blue'),
	('d10047', 'white', 'Spanish Carmine'),
	('e51a4c', 'white', 'Spanish Crimson'),
	('989898', 'black', 'Spanish Gray'),
	('009150', 'white', 'Spanish Green'),
	('e86100', 'black', 'Spanish Orange'),
	('f7bfbe', 'black', 'Spanish Pink'),
	('e60026', 'white', 'Spanish Red'),
	('00ffff', 'black', 'Aqua'),
	('4c2882', 'white', 'Spanish Violet'),
	('007f5c', 'white', 'Spanish Viridian'),
	('9e1316', 'white', 'Spartan Crimson'),
	('0fc0fc', 'black', 'Spiro Disco Ball'),
	('a7fc00', 'black', 'Spring Bud'),
	('00ff7f', 'black', 'Guppie Green'),
	('23297a', 'white', "St. Patrick's Blue"),
	('007bbb', 'white', 'Star Command Blue'),
	('4682b4', 'white', 'Steel Blue'),
	('cc33cc', 'white', 'Steel Pink'),
	('fada5e', 'black', 'Jonquil'),
	('990000', 'white', 'OU Crimson Red'),
	('4f666a', 'white', 'Stormcloud'),
	('e4d96f', 'black', 'Straw'),
	('fc5a8d', 'black', 'Strawberry'),
	('ffcc33', 'black', 'Sunglow'),
	('e3ab57', 'black', 'Sunray'),
	('fad6a5', 'black', 'Deep Champagne'),
	('fd5e53', 'black', 'Sunset Orange'),
	('cf6ba9', 'black', 'Super Pink'),
	('d2b48c', 'black', 'Tan'),
	('f94d00', 'black', 'Tangelo'),
	('f28500', 'black', 'Tangerine'),
	('ffcc00', 'black', 'Tangerine Yellow'),
	('e4717a', 'black', 'Candy Pink'),
	('483c32', 'white', 'Dark Lava'),
	('8b8589', 'black', 'Taupe Gray'),
	('cd5700', 'white', 'Tawny'),
	('d0f0c0', 'black', 'Tea Green'),
	('f4c2c2', 'black', 'Baby Pink'),
	('f88379', 'black', 'Congo Pink'),
	('008080', 'white', 'Teal'),
	('367588', 'white', 'Teal Blue'),
	('99e6b3', 'black', 'Teal Deer'),
	('00827f', 'white', 'Teal Green'),
	('cf3476', 'white', 'Telemagenta'),
	('cd5700', 'white', 'Tawny'),
	('e2725b', 'black', 'Terra Cotta'),
	('d8bfd8', 'black', 'Thistle'),
	('de6fa1', 'black', 'China Pink'),
	('fc89ac', 'black', 'Tickle Me Pink'),
	('0abab5', 'black', 'Tiffany Blue'),
	('e08d3c', 'black', "Tiger's Eye"),
	('dbd7d2', 'black', 'Timberwolf'),
	('eee600', 'black', 'Titanium Yellow'),
	('ff6347', 'black', 'Tomato'),
	('746cc0', 'white', 'Toolbox'),
	('ffc87c', 'black', 'Topaz'),
	('fd0e35', 'white', 'Scarlet'),
	('808080', 'white', 'Gray'),
	('00755e', 'white', 'Tropical Rain Forest'),
	('0073cf', 'white', 'True Blue'),
	('417dc1', 'white', 'Tufts Blue'),
	('ff878d', 'black', 'Tulip'),
	('deaa88', 'black', 'Tumbleweed'),
	('b57281', 'black', 'Turkish Rose'),
	('30d5c8', 'black', 'Turquoise'),
	('00ffef', 'black', 'Turquoise Blue'),
	('a0d6b4', 'black', 'Turquoise Green'),
	('fad6a5', 'black', 'Deep Champagne'),
	('6f4e37', 'white', 'Coffee'),
	('7c4848', 'white', 'Tuscan Red'),
	('c09999', 'black', 'Tuscany'),
	('4099ff', 'black', 'Tweeter blue'),
	('8a496b', 'white', 'Twilight Lavender'),
	('66023c', 'white', 'Imperial Purple'),
	('0033aa', 'white', 'UA Blue'),
	('d9004c', 'white', 'UA Red'),
	('536895', 'white', 'UCLA Blue'),
	('ffb300', 'black', 'UCLA Gold'),
	('3cd070', 'black', 'UFO Green'),
	('014421', 'white', 'Forest Green'),
	('7b1113', 'white', 'UP Maroon'),
	('004f98', 'white', 'USAFA Blue'),
	('990000', 'white', 'OU Crimson Red'),
	('ffcc00', 'black', 'Tangerine Yellow'),
	('8878c3', 'black', 'Ube'),
	('ff6fff', 'black', 'Shocking Pink'),
	('fc6c85', 'black', 'Ultra Red'),
	('120a8f', 'white', 'Ultramarine'),
	('4166f5', 'white', 'Ultramarine Blue'),
	('635147', 'white', 'Umber'),
	('ffddca', 'black', 'Unbleached Silk'),
	('5b92e5', 'black', 'United Nations Blue'),
	('ffff66', 'black', 'Unmellow Yellow'),
	('ae2029', 'white', 'Upsdell Red'),
	('e1ad21', 'black', 'Urobilin'),
	('d3003f', 'white', 'Utah Crimson'),
	('f3e5ab', 'black', 'Medium Champagne'),
	('f38fa9', 'black', 'Vanilla Ice'),
	('c5b358', 'black', 'Vegas Gold'),
	('c80815', 'white', 'Venetian Red'),
	('43b3ae', 'black', 'Verdigris'),
	('e34234', 'white', 'Cinnabar'),
	('d9603b', 'black', 'Medium Vermilion'),
	('a020f0', 'white', 'Purple'),
	('8f00ff', 'white', 'Electric Violet'),
	('8601af', 'white', 'Violet'),
	('7f00ff', 'white', 'Violet'),
	('ee82ee', 'black', 'Lavender Magenta'),
	('324ab2', 'white', 'Violet-blue'),
	('f75394', 'black', 'Violet-red'),
	('40826d', 'white', 'Viridian'),
	('009698', 'black', 'Viridian Green'),
	('922724', 'white', 'Vivid Auburn'),
	('9f1d35', 'white', 'Vivid Burgundy'),
	('da1d81', 'white', 'Vivid Cerise'),
	('cc00ff', 'white', 'Vivid Orchid'),
	('00ccff', 'black', 'Vivid Sky Blue'),
	('ffa089', 'black', 'Vivid Tangerine'),
	('9f00ff', 'white', 'Vivid Violet'),
	('004242', 'white', 'Warm Black'),
	('a4f4f9', 'black', 'Waterspout'),
	('645452', 'white', 'Wenge'),
	('f5deb3', 'black', 'Wheat'),
	('ffffff', 'black', 'White'),
	('f5f5f5', 'black', 'White Smoke'),
	('a2add0', 'black', 'Wild Blue Yonder'),
	('d470a2', 'black', 'Wild Orchid'),
	('ff43a4', 'black', 'Wild Strawberry'),
	('fc6c85', 'black', 'Ultra Red'),
	('fd5800', 'black', 'Willpower Orange'),
	('008080', 'white', 'Teal'),
	('004e98', 'white', 'Windows XP Desktop'),
	('ae6838', 'white', 'Windsor Tan'),
	('722f37', 'white', 'Puce Red'),
	('673147', 'white', 'Old Mauve'),
	('c9a0dc', 'black', 'Wisteria'),
	('c19a6b', 'black', 'Camel'),
	('738678', 'white', 'Xanadu'),
	('0f4d92', 'white', 'Yale Blue'),
	('1c2841', 'white', 'Yankees Blue'),
	('ffff00', 'black', 'Electric Yellow'),
	('fce883', 'black', 'Yellow'),
	('efcc00', 'black', 'Yellow'),
	('ffd300', 'black', 'Cyber Yellow'),
	('fedf00', 'black', 'Yellow'),
	('fefe33', 'black', 'Yellow'),
	('ffef00', 'black', 'Canary Yellow'),
	('ffae42', 'black', 'Yellow Orange'),
	('fff000', 'black', 'Yellow Rose'),
	('9acd32', 'black', 'Yellow-green'),
	('0014a8', 'white', 'Zaffre'),
	('2c1608', 'white', 'Zinnwaldite Brown'),
	('39a78e', 'black', 'Zomp'),
]
