# Generated by Django 3.2.5 on 2021-07-20 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='listed',
            field=models.BooleanField(default=True, help_text='Whether this page is listed.'),
        ),
        migrations.AddField(
            model_name='page',
            name='published',
            field=models.BooleanField(default=True, help_text='Whether this page is published.'),
        ),
    ]
