# Generated by Django 3.2.5 on 2021-07-24 00:09

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):
    dependencies = [
        ("info", "0002_auto_20210720_0624"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="content",
            field=markdownx.models.MarkdownxField(
                help_text="Markdown content for the page"
            ),
        ),
    ]
